package views.form;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author huutu
 */
public class FormCachLy extends javax.swing.JPanel {

    /**
     * Creates new form FormCachLy
     */
    public FormCachLy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        F0RadioButton = new javax.swing.JRadioButton();
        F1RadioButton = new javax.swing.JRadioButton();
        F2RadioButton = new javax.swing.JRadioButton();
        KhongRadioButton = new javax.swing.JRadioButton();
        DiaDiemDiChuyentextField = new views.swing.textfield.TextField();
        HoCamSotRadioButton = new javax.swing.JRadioButton();
        Kieu = new javax.swing.JLabel();
        HaiMuiTiemRadioButton = new javax.swing.JRadioButton();
        CMCDCovidtextField = new views.swing.textfield.TextField();
        SoMuiTiem = new javax.swing.JLabel();
        MotMuiTiemRadioButton = new javax.swing.JRadioButton();
        LanTestGanNhattextField = new views.swing.textfield.TextField();
        TinhTrangSucKhoe = new javax.swing.JLabel();
        KhongMuiTiemRadioButton = new javax.swing.JRadioButton();
        SaveButton = new views.swing.Button();
        ketQuaLanTestGanNhattextField = new views.swing.textfield.TextField();
        F1RadioButton1 = new javax.swing.JRadioButton();
        InButton = new views.swing.Button();

        F0RadioButton.setBackground(new java.awt.Color(245, 245, 245));
        F0RadioButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        F0RadioButton.setForeground(new java.awt.Color(153, 153, 153));
        F0RadioButton.setActionCommand("asdf");
        F0RadioButton.setLabel("F0");
        F0RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F0RadioButtonActionPerformed(evt);
            }
        });

        F1RadioButton.setBackground(new java.awt.Color(245, 245, 245));
        F1RadioButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        F1RadioButton.setForeground(new java.awt.Color(153, 153, 153));
        F1RadioButton.setLabel("F1");
        F1RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F1RadioButtonActionPerformed(evt);
            }
        });

        F2RadioButton.setBackground(new java.awt.Color(245, 245, 245));
        F2RadioButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        F2RadioButton.setForeground(new java.awt.Color(153, 153, 153));
        F2RadioButton.setLabel("F2");

        KhongRadioButton.setBackground(new java.awt.Color(245, 245, 245));
        KhongRadioButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        KhongRadioButton.setForeground(new java.awt.Color(153, 153, 153));
        KhongRadioButton.setLabel("Không");

        DiaDiemDiChuyentextField.setBackground(new java.awt.Color(245, 245, 245));
        DiaDiemDiChuyentextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        DiaDiemDiChuyentextField.setLabelText("ĐÃ ĐI ĐÂU TRONG 14 NGÀY (NHẬP ĐỊA ĐIỂM CÁCH NHAU BỞI \";\")");
        DiaDiemDiChuyentextField.setOpaque(false);
        DiaDiemDiChuyentextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaDiemDiChuyentextFieldActionPerformed(evt);
            }
        });

        HoCamSotRadioButton.setBackground(new java.awt.Color(245, 245, 245));
        HoCamSotRadioButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        HoCamSotRadioButton.setForeground(new java.awt.Color(153, 153, 153));
        HoCamSotRadioButton.setLabel("Ho, cảm, sốt");

        Kieu.setBackground(new java.awt.Color(245, 245, 245));
        Kieu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Kieu.setForeground(new java.awt.Color(153, 153, 153));
        Kieu.setText("KIỂU:");

        HaiMuiTiemRadioButton.setBackground(new java.awt.Color(245, 245, 245));
        HaiMuiTiemRadioButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        HaiMuiTiemRadioButton.setForeground(new java.awt.Color(153, 153, 153));
        HaiMuiTiemRadioButton.setLabel("2");
        HaiMuiTiemRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HaiMuiTiemRadioButtonActionPerformed(evt);
            }
        });

        CMCDCovidtextField.setBackground(new java.awt.Color(245, 245, 245));
        CMCDCovidtextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        CMCDCovidtextField.setLabelText("SỐ CMND/CCCD");
        CMCDCovidtextField.setOpaque(false);
        CMCDCovidtextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMCDCovidtextFieldActionPerformed(evt);
            }
        });

        SoMuiTiem.setBackground(new java.awt.Color(245, 245, 245));
        SoMuiTiem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SoMuiTiem.setForeground(new java.awt.Color(153, 153, 153));
        SoMuiTiem.setText("SỐ MŨI TIÊM:");

        MotMuiTiemRadioButton.setBackground(new java.awt.Color(245, 245, 245));
        MotMuiTiemRadioButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        MotMuiTiemRadioButton.setForeground(new java.awt.Color(153, 153, 153));
        MotMuiTiemRadioButton.setLabel("1");
        MotMuiTiemRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotMuiTiemRadioButtonActionPerformed(evt);
            }
        });

        LanTestGanNhattextField.setBackground(new java.awt.Color(245, 245, 245));
        LanTestGanNhattextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LanTestGanNhattextField.setLabelText("LẦN TEST GẦN NHẤT");
        LanTestGanNhattextField.setOpaque(false);
        LanTestGanNhattextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LanTestGanNhattextFieldActionPerformed(evt);
            }
        });

        TinhTrangSucKhoe.setBackground(new java.awt.Color(245, 245, 245));
        TinhTrangSucKhoe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TinhTrangSucKhoe.setForeground(new java.awt.Color(153, 153, 153));
        TinhTrangSucKhoe.setText("TÌNH TRẠNG SỨC KHỎE:");

        KhongMuiTiemRadioButton.setBackground(new java.awt.Color(245, 245, 245));
        KhongMuiTiemRadioButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        KhongMuiTiemRadioButton.setForeground(new java.awt.Color(153, 153, 153));
        KhongMuiTiemRadioButton.setLabel("0");

        SaveButton.setBackground(new java.awt.Color(89, 89, 255));
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setToolTipText("");
        SaveButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        SaveButton.setLabel("LƯU");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        ketQuaLanTestGanNhattextField.setBackground(new java.awt.Color(245, 245, 245));
        ketQuaLanTestGanNhattextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ketQuaLanTestGanNhattextField.setLabelText("KẾT QUẢ LẦN TEST GẦN NHẤT");
        ketQuaLanTestGanNhattextField.setOpaque(false);
        ketQuaLanTestGanNhattextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketQuaLanTestGanNhattextFieldActionPerformed(evt);
            }
        });

        F1RadioButton1.setBackground(new java.awt.Color(245, 245, 245));
        F1RadioButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        F1RadioButton1.setForeground(new java.awt.Color(153, 153, 153));
        F1RadioButton1.setText("Không");

        InButton.setBackground(new java.awt.Color(89, 89, 255));
        InButton.setForeground(new java.awt.Color(255, 255, 255));
        InButton.setToolTipText("");
        InButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        InButton.setLabel("IN");
        InButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(348, 348, 348)
                                        .addComponent(F2RadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Kieu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(F1RadioButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(F0RadioButton)
                                        .addGap(39, 39, 39)
                                        .addComponent(F1RadioButton))
                                    .addComponent(CMCDCovidtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(SoMuiTiem, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(KhongMuiTiemRadioButton)
                                            .addGap(50, 50, 50)
                                            .addComponent(MotMuiTiemRadioButton)
                                            .addGap(50, 50, 50)
                                            .addComponent(HaiMuiTiemRadioButton))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(TinhTrangSucKhoe, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(HoCamSotRadioButton)
                                            .addGap(27, 27, 27)
                                            .addComponent(KhongRadioButton)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(201, 201, 201)
                                .addComponent(InButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DiaDiemDiChuyentextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LanTestGanNhattextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ketQuaLanTestGanNhattextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(CMCDCovidtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kieu)
                    .addComponent(F1RadioButton1)
                    .addComponent(F0RadioButton)
                    .addComponent(F1RadioButton)
                    .addComponent(F2RadioButton))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TinhTrangSucKhoe)
                    .addComponent(HoCamSotRadioButton)
                    .addComponent(KhongRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SoMuiTiem)
                    .addComponent(KhongMuiTiemRadioButton)
                    .addComponent(MotMuiTiemRadioButton)
                    .addComponent(HaiMuiTiemRadioButton))
                .addGap(18, 18, 18)
                .addComponent(LanTestGanNhattextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ketQuaLanTestGanNhattextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DiaDiemDiChuyentextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void F0RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F0RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F0RadioButtonActionPerformed

    private void F1RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F1RadioButtonActionPerformed

    private void DiaDiemDiChuyentextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaDiemDiChuyentextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaDiemDiChuyentextFieldActionPerformed

    private void HaiMuiTiemRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HaiMuiTiemRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HaiMuiTiemRadioButtonActionPerformed

    private void CMCDCovidtextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMCDCovidtextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CMCDCovidtextFieldActionPerformed

    private void MotMuiTiemRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotMuiTiemRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotMuiTiemRadioButtonActionPerformed

    private void LanTestGanNhattextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LanTestGanNhattextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LanTestGanNhattextFieldActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
       

    }//GEN-LAST:event_SaveButtonActionPerformed

    private void ketQuaLanTestGanNhattextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketQuaLanTestGanNhattextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ketQuaLanTestGanNhattextFieldActionPerformed

    private void InButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private views.swing.textfield.TextField CMCDCovidtextField;
    private views.swing.textfield.TextField DiaDiemDiChuyentextField;
    private javax.swing.JRadioButton F0RadioButton;
    private javax.swing.JRadioButton F1RadioButton;
    private javax.swing.JRadioButton F1RadioButton1;
    private javax.swing.JRadioButton F2RadioButton;
    private javax.swing.JRadioButton HaiMuiTiemRadioButton;
    private javax.swing.JRadioButton HoCamSotRadioButton;
    private views.swing.Button InButton;
    private javax.swing.JRadioButton KhongMuiTiemRadioButton;
    private javax.swing.JRadioButton KhongRadioButton;
    private javax.swing.JLabel Kieu;
    private views.swing.textfield.TextField LanTestGanNhattextField;
    private javax.swing.JRadioButton MotMuiTiemRadioButton;
    private views.swing.Button SaveButton;
    private javax.swing.JLabel SoMuiTiem;
    private javax.swing.JLabel TinhTrangSucKhoe;
    private views.swing.textfield.TextField ketQuaLanTestGanNhattextField;
    // End of variables declaration//GEN-END:variables
}
