/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.form;

import com.itextpdf.io.font.PdfEncodings;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import controllers.ControllerNhanKhau;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import models.ModelNhanKhau;
import test.Main;
import views.dialog.MessageConfirm;

/**
 *
 * @author HO ANH
 */
public class FormDanhMucNhanKhau extends javax.swing.JPanel {

    /**
     * Creates new form FormDanhMucNhanKhau
     */
    public FormDanhMucNhanKhau() {
        
        initComponents();
        table1.fixTable(jScrollPane1);
        try{
           initDataTable();
        }catch(Exception e){};
    }
    
    private void showMessage(String message, int func) {
        MessageConfirm obj = new MessageConfirm(Main.getFrames()[0], true, func);
        obj.showMessage(message);
    }
    
    public void initDataTable() throws SQLException, ClassNotFoundException {
        ControllerNhanKhau NhanKhau = new ControllerNhanKhau();
        ArrayList<ModelNhanKhau> resultListNhanKhau = new ArrayList<ModelNhanKhau>();

        resultListNhanKhau = NhanKhau.selectDanhMucNhanKhau(); 
        for(int i=0; i<resultListNhanKhau.size(); i++){
            table1.addRow(resultListNhanKhau.get(i).toRowTableNhanKhau());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new views.swing.table.Table();
        ButtonTimKiem = new views.swing.Button();

        setBackground(new java.awt.Color(245, 245, 245));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("DANH MỤC NHÂN KHẨU");

        table1.setBackground(new java.awt.Color(245, 245, 245));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ tên", "Ngày sinh", "Giới tính", "Nghề nghiệp", "Dân tộc", "Nơi ở hiện tại", "Nơi thường trú"
            }
        ));
        jScrollPane1.setViewportView(table1);
        if (table1.getColumnModel().getColumnCount() > 0) {
            table1.getColumnModel().getColumn(1).setPreferredWidth(30);
            table1.getColumnModel().getColumn(2).setPreferredWidth(15);
        }

        ButtonTimKiem.setBackground(new java.awt.Color(89, 89, 255));
        ButtonTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        ButtonTimKiem.setText("IN PDF");
        ButtonTimKiem.setToolTipText("");
        ButtonTimKiem.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ButtonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 277, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(0, 277, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTimKiemActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            String currentDirectory = System.getProperty("user.dir");
            chooser.setSelectedFile(new File("Untitled.pdf"));
            chooser.setCurrentDirectory(new File(currentDirectory));
            chooser.showSaveDialog(null);
            String path = chooser.getSelectedFile().getAbsolutePath();
            PdfWriter writer = new PdfWriter(path);
            PdfDocument pdf = new PdfDocument(writer);
            pdf.addNewPage();
            PdfFont font = PdfFontFactory.createFont(".\\resources\\fonts\\calibri.ttf", PdfEncodings.IDENTITY_H);

            Document document = new Document(pdf);
            String para1 = "Danh mục nhân khẩu: ";
            Paragraph paragraph1 = new Paragraph(para1).setFont(font);
            document.add(paragraph1);


            Table table = new Table(new float[]{100F, 70F, 50F, 70F, 70F, 150F, 150F});

            Cell cell = new Cell();
            cell.add(new Paragraph("Họ tên").setFont(font));
            table.addCell(cell);

            cell = new Cell();
            cell.add(new Paragraph("Ngày sinh").setFont(font));
            table.addCell(cell);

            cell = new Cell();
            cell.add(new Paragraph("Giới tính").setFont(font));
            table.addCell(cell);
            
            cell = new Cell();
            cell.add(new Paragraph("Nghề nghiệp").setFont(font));
            table.addCell(cell);
            
            cell = new Cell();
            cell.add(new Paragraph("Dân tộc").setFont(font));
            table.addCell(cell);
            
            cell = new Cell();
            cell.add(new Paragraph("Nơi ở hiện tại").setFont(font));
            table.addCell(cell);
            
            cell = new Cell();
            cell.add(new Paragraph("Nơi thường trú").setFont(font));
            table.addCell(cell);

            ArrayList<String> arr = table1.readTable();
            for (int i = 0; i < arr.size(); ++i) {
                cell = new Cell();
                cell.add(new Paragraph(arr.get(i)).setFont(font));
                table.addCell(cell);
            }

            document.add(table);

            document.close();
            showMessage("Bạn đã in PDF thành công", 1);
            System.out.println("PDF created");
        } catch (Exception e) {
          System.out.println(e);
        }
    }//GEN-LAST:event_ButtonTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private views.swing.Button ButtonTimKiem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private views.swing.table.Table table1;
    // End of variables declaration//GEN-END:variables
}
