/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.form;

import controllers.ControllerKhaiTu;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.ModelKhaiTu;

/**
 *
 * @author HO ANH
 */
public class FormBaoTu extends javax.swing.JPanel {

    /**
     * Creates new form FormBaoTu
     */
    public FormBaoTu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NhapSoHoKhautextField = new views.swing.textfield.TextField();
        NgayMattextField = new views.swing.textfield.TextField();
        NgayKhaitextField = new views.swing.textfield.TextField();
        lyDotextField = new views.swing.textfield.TextField();
        SaveButton = new views.swing.Button();
        InButton = new views.swing.Button();
        CMNDCCCDBaoTutextField = new views.swing.textfield.TextField();
        NguoiKhaitextField = new views.swing.textfield.TextField();

        setBackground(new java.awt.Color(245, 245, 245));

        NhapSoHoKhautextField.setBackground(new java.awt.Color(245, 245, 245));
        NhapSoHoKhautextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NhapSoHoKhautextField.setLabelText("NHẬP SỐ HỘ KHẨU");
        NhapSoHoKhautextField.setOpaque(false);
        NhapSoHoKhautextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhapSoHoKhautextFieldActionPerformed(evt);
            }
        });

        NgayMattextField.setBackground(new java.awt.Color(245, 245, 245));
        NgayMattextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NgayMattextField.setLabelText("NGÀY MẤT");
        NgayMattextField.setOpaque(false);
        NgayMattextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NgayMattextFieldActionPerformed(evt);
            }
        });

        NgayKhaitextField.setBackground(new java.awt.Color(245, 245, 245));
        NgayKhaitextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NgayKhaitextField.setLabelText("NGÀY KHAI");
        NgayKhaitextField.setOpaque(false);
        NgayKhaitextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NgayKhaitextFieldActionPerformed(evt);
            }
        });

        lyDotextField.setBackground(new java.awt.Color(245, 245, 245));
        lyDotextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lyDotextField.setLabelText("LÝ DO");
        lyDotextField.setOpaque(false);
        lyDotextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lyDotextFieldActionPerformed(evt);
            }
        });

        SaveButton.setBackground(new java.awt.Color(89, 89, 255));
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setToolTipText("");
        SaveButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        SaveButton.setLabel("LƯU");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        InButton.setBackground(new java.awt.Color(89, 89, 255));
        InButton.setForeground(new java.awt.Color(255, 255, 255));
        InButton.setToolTipText("");
        InButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        InButton.setLabel("IN");
        InButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InButtonActionPerformed(evt);
            }
        });

        CMNDCCCDBaoTutextField.setBackground(new java.awt.Color(245, 245, 245));
        CMNDCCCDBaoTutextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        CMNDCCCDBaoTutextField.setLabelText("NHẬP SỐ CMND/CCCD");
        CMNDCCCDBaoTutextField.setOpaque(false);
        CMNDCCCDBaoTutextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMNDCCCDBaoTutextFieldActionPerformed(evt);
            }
        });

        NguoiKhaitextField.setBackground(new java.awt.Color(245, 245, 245));
        NguoiKhaitextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NguoiKhaitextField.setLabelText("NGƯỜI KHAI");
        NguoiKhaitextField.setOpaque(false);
        NguoiKhaitextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NguoiKhaitextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NguoiKhaitextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lyDotextField, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(522, 522, 522)
                            .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(94, 94, 94)
                            .addComponent(InButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(NhapSoHoKhautextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(104, 104, 104))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(NgayKhaitextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CMNDCCCDBaoTutextField, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                                .addComponent(NgayMattextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NhapSoHoKhautextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMNDCCCDBaoTutextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NgayKhaitextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NgayMattextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lyDotextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NguoiKhaitextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NhapSoHoKhautextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhapSoHoKhautextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NhapSoHoKhautextFieldActionPerformed

    private void NgayMattextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NgayMattextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NgayMattextFieldActionPerformed

    private void NgayKhaitextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NgayKhaitextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NgayKhaitextFieldActionPerformed

    private void lyDotextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lyDotextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lyDotextFieldActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
           try{
               ControllerKhaiTu khaiTuController = new ControllerKhaiTu();
               ModelKhaiTu x = new ModelKhaiTu(NhapSoHoKhautextField.getText(), NguoiKhaitextField.getText(), CMNDCCCDBaoTutextField.getText(), NgayMattextField.getText(), lyDotextField.getText(), "user1", NgayKhaitextField.getText());
       
        try {
            khaiTuController.insertKhaiTu(x);
        } catch (SQLException ex) {
            Logger.getLogger(FormKhaiBaoCovid.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormKhaiBaoCovid.class.getName()).log(Level.SEVERE, null, ex);
        }
        CMNDCCCDBaoTutextField.setText("");
        NguoiKhaitextField.setText("");
        NhapSoHoKhautextField.setText("");
        NgayMattextField.setText("");
        lyDotextField.setText("");
        NgayKhaitextField.setText("");
        }
        catch(Exception ex){
        JOptionPane.showMessageDialog(null, "Nhap sai");
        
    }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void InButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InButtonActionPerformed

    private void CMNDCCCDBaoTutextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMNDCCCDBaoTutextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CMNDCCCDBaoTutextFieldActionPerformed

    private void NguoiKhaitextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NguoiKhaitextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NguoiKhaitextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private views.swing.textfield.TextField CMNDCCCDBaoTutextField;
    private views.swing.Button InButton;
    private views.swing.textfield.TextField NgayKhaitextField;
    private views.swing.textfield.TextField NgayMattextField;
    private views.swing.textfield.TextField NguoiKhaitextField;
    private views.swing.textfield.TextField NhapSoHoKhautextField;
    private views.swing.Button SaveButton;
    private views.swing.textfield.TextField lyDotextField;
    // End of variables declaration//GEN-END:variables
}
