/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.form;

/**
 *
 * @author HO ANH
 */
public class FormKhaiBaoCovid extends javax.swing.JPanel {

    /**
     * Creates new form FormKhaiBaoCovid
     */
    public FormKhaiBaoCovid() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KieuButtonGroup = new javax.swing.ButtonGroup();
        TinhTrangSucKhoeButtonGroup = new javax.swing.ButtonGroup();
        SoMuiTiemButton = new javax.swing.ButtonGroup();
        CMCDCovidtextField = new views.swing.textfield.TextField();
        DiaDiemDiChuyentextField = new views.swing.textfield.TextField();
        LanTestGanNhattextField = new views.swing.textfield.TextField();
        Kieu = new javax.swing.JLabel();
        SoMuiTiem = new javax.swing.JLabel();
        TinhTrangSucKhoe = new javax.swing.JLabel();
        SaveButton = new views.swing.Button();
        InButton = new views.swing.Button();
        jPanel1 = new javax.swing.JPanel();
        F0RadioButton = new javax.swing.JRadioButton();
        F1RadioButton = new javax.swing.JRadioButton();
        F2RadioButton = new javax.swing.JRadioButton();
        KhongRadioButton = new javax.swing.JRadioButton();
        HoCamSotRadioButton = new javax.swing.JRadioButton();
        HaiMuiTiemRadioButton = new javax.swing.JRadioButton();
        MotMuiTiemRadioButton = new javax.swing.JRadioButton();
        KhongMuiTiemRadioButton = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(245, 245, 245));

        CMCDCovidtextField.setBackground(new java.awt.Color(245, 245, 245));
        CMCDCovidtextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        CMCDCovidtextField.setLabelText("SỐ CMND/CCCD");
        CMCDCovidtextField.setOpaque(false);
        CMCDCovidtextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMCDCovidtextFieldActionPerformed(evt);
            }
        });

        DiaDiemDiChuyentextField.setBackground(new java.awt.Color(245, 245, 245));
        DiaDiemDiChuyentextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        DiaDiemDiChuyentextField.setLabelText("ĐÃ ĐI ĐÂU TRONG 14 NGÀY (NHẬP ĐỊA ĐIỂM CÁCH NHAU BỞI \";\")");
        DiaDiemDiChuyentextField.setOpaque(false);
        DiaDiemDiChuyentextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaDiemDiChuyentextFieldActionPerformed(evt);
            }
        });

        LanTestGanNhattextField.setBackground(new java.awt.Color(245, 245, 245));
        LanTestGanNhattextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LanTestGanNhattextField.setLabelText("LẦN TEST GẦN NHẤT");
        LanTestGanNhattextField.setOpaque(false);
        LanTestGanNhattextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LanTestGanNhattextFieldActionPerformed(evt);
            }
        });

        Kieu.setBackground(new java.awt.Color(245, 245, 245));
        Kieu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Kieu.setForeground(new java.awt.Color(153, 153, 153));
        Kieu.setText("KIỂU:");

        SoMuiTiem.setBackground(new java.awt.Color(245, 245, 245));
        SoMuiTiem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SoMuiTiem.setForeground(new java.awt.Color(153, 153, 153));
        SoMuiTiem.setText("SỐ MŨI TIÊM:");

        TinhTrangSucKhoe.setBackground(new java.awt.Color(245, 245, 245));
        TinhTrangSucKhoe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TinhTrangSucKhoe.setForeground(new java.awt.Color(153, 153, 153));
        TinhTrangSucKhoe.setText("TÌNH TRẠNG SỨC KHỎE:");

        SaveButton.setBackground(new java.awt.Color(89, 89, 255));
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setToolTipText("");
        SaveButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        SaveButton.setLabel("LƯU");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        InButton.setBackground(new java.awt.Color(89, 89, 255));
        InButton.setForeground(new java.awt.Color(255, 255, 255));
        InButton.setToolTipText("");
        InButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        InButton.setLabel("IN");
        InButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        F0RadioButton.setBackground(new java.awt.Color(245, 245, 245));
        KieuButtonGroup.add(F0RadioButton);
        F0RadioButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        F0RadioButton.setForeground(new java.awt.Color(153, 153, 153));
        F0RadioButton.setLabel("F0");

        F1RadioButton.setBackground(new java.awt.Color(245, 245, 245));
        KieuButtonGroup.add(F1RadioButton);
        F1RadioButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        F1RadioButton.setForeground(new java.awt.Color(153, 153, 153));
        F1RadioButton.setLabel("F1");

        F2RadioButton.setBackground(new java.awt.Color(245, 245, 245));
        KieuButtonGroup.add(F2RadioButton);
        F2RadioButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        F2RadioButton.setForeground(new java.awt.Color(153, 153, 153));
        F2RadioButton.setLabel("F2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(F0RadioButton)
                .addGap(53, 53, 53)
                .addComponent(F1RadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(F2RadioButton)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(F0RadioButton)
                    .addComponent(F2RadioButton)
                    .addComponent(F1RadioButton))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        KhongRadioButton.setBackground(new java.awt.Color(245, 245, 245));
        TinhTrangSucKhoeButtonGroup.add(KhongRadioButton);
        KhongRadioButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        KhongRadioButton.setForeground(new java.awt.Color(153, 153, 153));
        KhongRadioButton.setLabel("Không");

        HoCamSotRadioButton.setBackground(new java.awt.Color(245, 245, 245));
        TinhTrangSucKhoeButtonGroup.add(HoCamSotRadioButton);
        HoCamSotRadioButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        HoCamSotRadioButton.setForeground(new java.awt.Color(153, 153, 153));
        HoCamSotRadioButton.setLabel("Ho, cảm, sốt");

        HaiMuiTiemRadioButton.setBackground(new java.awt.Color(245, 245, 245));
        SoMuiTiemButton.add(HaiMuiTiemRadioButton);
        HaiMuiTiemRadioButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        HaiMuiTiemRadioButton.setForeground(new java.awt.Color(153, 153, 153));
        HaiMuiTiemRadioButton.setLabel("2");

        MotMuiTiemRadioButton.setBackground(new java.awt.Color(245, 245, 245));
        SoMuiTiemButton.add(MotMuiTiemRadioButton);
        MotMuiTiemRadioButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        MotMuiTiemRadioButton.setForeground(new java.awt.Color(153, 153, 153));
        MotMuiTiemRadioButton.setLabel("1");

        KhongMuiTiemRadioButton.setBackground(new java.awt.Color(245, 245, 245));
        SoMuiTiemButton.add(KhongMuiTiemRadioButton);
        KhongMuiTiemRadioButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        KhongMuiTiemRadioButton.setForeground(new java.awt.Color(153, 153, 153));
        KhongMuiTiemRadioButton.setLabel("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DiaDiemDiChuyentextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LanTestGanNhattextField, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CMCDCovidtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TinhTrangSucKhoe, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Kieu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(HoCamSotRadioButton)
                                        .addGap(49, 49, 49)
                                        .addComponent(KhongRadioButton))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SoMuiTiem, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(KhongMuiTiemRadioButton)
                                .addGap(65, 65, 65)
                                .addComponent(MotMuiTiemRadioButton)
                                .addGap(47, 47, 47)
                                .addComponent(HaiMuiTiemRadioButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219)
                .addComponent(InButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(CMCDCovidtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Kieu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TinhTrangSucKhoe)
                    .addComponent(HoCamSotRadioButton)
                    .addComponent(KhongRadioButton))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SoMuiTiem)
                    .addComponent(KhongMuiTiemRadioButton)
                    .addComponent(MotMuiTiemRadioButton)
                    .addComponent(HaiMuiTiemRadioButton))
                .addGap(18, 18, 18)
                .addComponent(LanTestGanNhattextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DiaDiemDiChuyentextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CMCDCovidtextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMCDCovidtextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CMCDCovidtextFieldActionPerformed

    private void DiaDiemDiChuyentextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaDiemDiChuyentextFieldActionPerformed
        // TODO add your handling code her
        
    }//GEN-LAST:event_DiaDiemDiChuyentextFieldActionPerformed

    private void LanTestGanNhattextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LanTestGanNhattextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LanTestGanNhattextFieldActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void InButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private views.swing.textfield.TextField CMCDCovidtextField;
    private views.swing.textfield.TextField DiaDiemDiChuyentextField;
    private javax.swing.JRadioButton F0RadioButton;
    private javax.swing.JRadioButton F1RadioButton;
    private javax.swing.JRadioButton F2RadioButton;
    private javax.swing.JRadioButton HaiMuiTiemRadioButton;
    private javax.swing.JRadioButton HoCamSotRadioButton;
    private views.swing.Button InButton;
    private javax.swing.JRadioButton KhongMuiTiemRadioButton;
    private javax.swing.JRadioButton KhongRadioButton;
    private javax.swing.JLabel Kieu;
    private javax.swing.ButtonGroup KieuButtonGroup;
    private views.swing.textfield.TextField LanTestGanNhattextField;
    private javax.swing.JRadioButton MotMuiTiemRadioButton;
    private views.swing.Button SaveButton;
    private javax.swing.JLabel SoMuiTiem;
    private javax.swing.ButtonGroup SoMuiTiemButton;
    private javax.swing.JLabel TinhTrangSucKhoe;
    private javax.swing.ButtonGroup TinhTrangSucKhoeButtonGroup;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
