/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.form;

/**
 *
 * @author HO ANH
 */
public class FormKhaiBaoCovid extends javax.swing.JPanel {

    /**
     * Creates new form FormKhaiBaoCovid
     */
    public FormKhaiBaoCovid() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KhongMuiTiemCheckbox = new java.awt.Checkbox();
        HaiMuiTiemCheckbox = new java.awt.Checkbox();
        HoCamSotCheckbox = new java.awt.Checkbox();
        KhongSaoCheckbox = new java.awt.Checkbox();
        F2Checkbox = new java.awt.Checkbox();
        MotMuiTiemCheckbox = new java.awt.Checkbox();
        F1Checkbox = new java.awt.Checkbox();
        F0Checkbox = new java.awt.Checkbox();
        CMCDCovidtextField = new views.swing.textfield.TextField();
        DiaDiemDiChuyentextField = new views.swing.textfield.TextField();
        LanTestGanNhattextField = new views.swing.textfield.TextField();
        Kieu = new javax.swing.JLabel();
        SoMuiTiem = new javax.swing.JLabel();
        TinhTrangSucKhoe = new javax.swing.JLabel();
        SaveButton = new views.swing.Button();
        InButton = new views.swing.Button();

        setBackground(new java.awt.Color(245, 245, 245));

        KhongMuiTiemCheckbox.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        KhongMuiTiemCheckbox.setForeground(new java.awt.Color(153, 153, 153));
        KhongMuiTiemCheckbox.setLabel("0");

        HaiMuiTiemCheckbox.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        HaiMuiTiemCheckbox.setForeground(new java.awt.Color(153, 153, 153));
        HaiMuiTiemCheckbox.setLabel("2");

        HoCamSotCheckbox.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        HoCamSotCheckbox.setForeground(new java.awt.Color(153, 153, 153));
        HoCamSotCheckbox.setLabel("Ho, cảm, sốt,...");

        KhongSaoCheckbox.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        KhongSaoCheckbox.setForeground(new java.awt.Color(153, 153, 153));
        KhongSaoCheckbox.setLabel("Không");

        F2Checkbox.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        F2Checkbox.setForeground(new java.awt.Color(153, 153, 153));
        F2Checkbox.setLabel("F2");

        MotMuiTiemCheckbox.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        MotMuiTiemCheckbox.setForeground(new java.awt.Color(153, 153, 153));
        MotMuiTiemCheckbox.setLabel("1");

        F1Checkbox.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        F1Checkbox.setForeground(new java.awt.Color(153, 153, 153));
        F1Checkbox.setLabel("F1");

        F0Checkbox.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        F0Checkbox.setForeground(new java.awt.Color(153, 153, 153));
        F0Checkbox.setLabel("F0");

        CMCDCovidtextField.setBackground(new java.awt.Color(245, 245, 245));
        CMCDCovidtextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        CMCDCovidtextField.setLabelText("SỐ CMND/CCCD");
        CMCDCovidtextField.setOpaque(false);
        CMCDCovidtextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMCDCovidtextFieldActionPerformed(evt);
            }
        });

        DiaDiemDiChuyentextField.setBackground(new java.awt.Color(245, 245, 245));
        DiaDiemDiChuyentextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        DiaDiemDiChuyentextField.setLabelText("ĐÃ ĐI ĐÂU TRONG 14 NGÀY");
        DiaDiemDiChuyentextField.setOpaque(false);
        DiaDiemDiChuyentextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaDiemDiChuyentextFieldActionPerformed(evt);
            }
        });

        LanTestGanNhattextField.setBackground(new java.awt.Color(245, 245, 245));
        LanTestGanNhattextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LanTestGanNhattextField.setLabelText("LẦN TEST GẦN NHẤT");
        LanTestGanNhattextField.setOpaque(false);
        LanTestGanNhattextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LanTestGanNhattextFieldActionPerformed(evt);
            }
        });

        Kieu.setBackground(new java.awt.Color(245, 245, 245));
        Kieu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Kieu.setForeground(new java.awt.Color(153, 153, 153));
        Kieu.setText("KIỂU:");

        SoMuiTiem.setBackground(new java.awt.Color(245, 245, 245));
        SoMuiTiem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SoMuiTiem.setForeground(new java.awt.Color(153, 153, 153));
        SoMuiTiem.setText("SỐ MŨI TIÊM:");

        TinhTrangSucKhoe.setBackground(new java.awt.Color(245, 245, 245));
        TinhTrangSucKhoe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TinhTrangSucKhoe.setForeground(new java.awt.Color(153, 153, 153));
        TinhTrangSucKhoe.setText("TÌNH TRẠNG SỨC KHỎE:");

        SaveButton.setBackground(new java.awt.Color(89, 89, 255));
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setToolTipText("");
        SaveButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        SaveButton.setLabel("LƯU");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        InButton.setBackground(new java.awt.Color(89, 89, 255));
        InButton.setForeground(new java.awt.Color(255, 255, 255));
        InButton.setToolTipText("");
        InButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        InButton.setLabel("IN");
        InButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DiaDiemDiChuyentextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(214, 214, 214)
                                                .addComponent(KhongMuiTiemCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(MotMuiTiemCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(SoMuiTiem, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40)
                                        .addComponent(HaiMuiTiemCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(LanTestGanNhattextField, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TinhTrangSucKhoe, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(HoCamSotCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(KhongSaoCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Kieu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addComponent(F0Checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(F1Checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(F2Checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CMCDCovidtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218)
                .addComponent(InButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(CMCDCovidtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Kieu)
                    .addComponent(F1Checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F0Checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F2Checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KhongSaoCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoCamSotCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TinhTrangSucKhoe))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SoMuiTiem, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(KhongMuiTiemCheckbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MotMuiTiemCheckbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HaiMuiTiemCheckbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LanTestGanNhattextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DiaDiemDiChuyentextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CMCDCovidtextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMCDCovidtextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CMCDCovidtextFieldActionPerformed

    private void DiaDiemDiChuyentextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaDiemDiChuyentextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaDiemDiChuyentextFieldActionPerformed

    private void LanTestGanNhattextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LanTestGanNhattextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LanTestGanNhattextFieldActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void InButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private views.swing.textfield.TextField CMCDCovidtextField;
    private views.swing.textfield.TextField DiaDiemDiChuyentextField;
    private java.awt.Checkbox F0Checkbox;
    private java.awt.Checkbox F1Checkbox;
    private java.awt.Checkbox F2Checkbox;
    private java.awt.Checkbox HaiMuiTiemCheckbox;
    private java.awt.Checkbox HoCamSotCheckbox;
    private views.swing.Button InButton;
    private java.awt.Checkbox KhongMuiTiemCheckbox;
    private java.awt.Checkbox KhongSaoCheckbox;
    private javax.swing.JLabel Kieu;
    private views.swing.textfield.TextField LanTestGanNhattextField;
    private java.awt.Checkbox MotMuiTiemCheckbox;
    private views.swing.Button SaveButton;
    private javax.swing.JLabel SoMuiTiem;
    private javax.swing.JLabel TinhTrangSucKhoe;
    // End of variables declaration//GEN-END:variables
}
